baseURL: 'https://antoinejeanson.github.io/'
languageCode: 'en-us'
title: 'Antoine Jeanson'
theme: 'PaperMod'

menu:
  main:
  - name: Home
    pageRef: /
    weight: 10
  - name: Blog
    pageRef: /blog
    weight: 20
  - name: About
    pageRef: /about
    weight: 30

params:
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
