baseURL: 'https://antoinejeanson.github.io/'
languageCode: 'en-us'
title: 'Antoine Jeanson'
theme: 'PaperMod'

menu:
  main:
  - name: Home
    pageRef: /
    weight: 10
  - name: Blog
    pageRef: /blog
    weight: 20
  - name: About
    pageRef: /about
    weight: 30

params:
  profileMode:
    enabled: true
    title: Antoine Jeanson
    subtitle: Engineer | Maker | Spaceflight enthusiast
    imageUrl: images/home_portrait.jpg
    imageTitle: A picture of me
    imageWidth: 240
    imageHeight: 240

  socialIcons:
    - name: github
      url: "https://github.com/antoinejeanson"
    - name: linkedIn
      url: "https://www.linkedin.com/in/antoinejeanson/"
  
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
